### PR TITLE
LPS-108500 Add title attr for truncate text

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
citr

**Comment by boton** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/2152.

**Comment by AliciaGarciaGarcia** [comment]
Pull request submitted to https://github.com/wincent/liferay-portal/pull/172.

**Comment by AliciaGarciaGarcia** [comment]
Pull request submitted to https://github.com/boton/liferay-portal/pull/145.

**Pull request closed without merging**
