### PR TITLE
LPS-106702 Rename fields of custom meta tags

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:seo

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83019. [See changes here.](https://github.com/AliciaGarciaGarcia/liferay-portal/compare/ebe568607c7f~1...ebe568607c7f)

**Pull request closed without merging**
