### PR TITLE
LPS 123054

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1133.

**Pull request closed without merging**
