### PR TITLE
LPS-100969 Auto SF

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
Pull request submitted to https://github.com/boton/liferay-portal/pull/93. [See changes here.](https://github.com/AliciaGarciaGarcia/liferay-portal/compare/670130ad823a~1...670130ad823a)

**Pull request closed without merging**
